### ISSUE TITLE
Certain metrics populating on one Windows server, but not the other?

### ISSUE THREAD

**Issue by m0ussaka** [prometheus-community/windows_exporter#1014]
Preface: New to Prometheus and windows_exporter. Trying to figure out why I'm getting certain metrics from one server, but not the other. Is there a way to force the population of certain values?

Both servers are 2012R2
Running version 0.18.1 installed with default values from the .msi

While searching /metrics page on each machine, I'm missing these values on one that are causing No Data to show on my dashboard.

`windows_os_physical_memory_free_bytes`
`windows_os_processes`
`windows_os_time`

I saw in another topic someone asked to make sure the `os` collector is running. How do I do this?

**Comment by breed808** [comment]
The `os` collector is a default collector, so it will be enabled as you've installed with default values.

While some of these could be unavailable due to underlying issues, the `windows_os_time` metric is provided by `currentTime.Unix()` which makes its absence quite unusual.

Are there any major differences between these two hosts? E.G. operating system version, installed components, etc.
It would also be worth checking the value of the `windows_exporter_collector_success` metric to see if the `os` collector is failing. Enabling debug output for the exporter might provide additional troubleshooting information.

**Comment by thierryVCL** [comment]
Hello We have the same issue . In our case it's related to an invalid configuration of the swap ( one page file is declared on a non existing drive)  which make the os collector not completing its collection.
The fix was already provided and is merged : https://github.com/prometheus-community/windows_exporter/issues/939.
I guess it should be included in the next release. When do you plan to release the next version of the windows_exporter ?

Thanks

**Comment by m0ussaka** [comment]
> 

Thanks for the info. I guess I'll just hold off and hope the new version pushes out soon.
