### ISSUE TITLE
Debug Symbols / PDB needed for investigation

### ISSUE THREAD

**Issue by Sarkie** [prometheus-community/windows_exporter#1032]
Hi,

When trying to start windows_exporter via Service or via Command Line it just hangs, nothing is logged, nothing happens.

Only thing that can be seen in ProcMon are some threads being created and sitting there.

If you could possibly provide the PDBs, then I can monitor and figure out what it is hanging on.

This is 1 server out of fleet, so we are a bit confused what it's doing as it doesn't seem to be even loading the app properly

Thanks

**Comment by breed808** [comment]
Hi Sarkie, if you're looking to attach a debugger to the exporter, there is some official [Golang documentation available](https://go.dev/doc/gdb). As mentioned in the link, Delve is a nicer debugging experience.

The only reference to PDB files I've found has been for Visual Studio; I don't believe Golang has support for creation of these files for debugging, but I'm happy to be wrong about that.

**Comment by Sarkie** [comment]
https://zetcode.com/golang/build/
 We run the program.

$ file simple.exe
simple.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows

external PDB, we should have those PDBs somewhere if you are building with debugging enabled, to enable the symbols afaik

**Comment by Sarkie** [comment]
@breed808 Based on the stack trace, you are connecting to WMI before you are logging anything, is this right?
Or is just loading the fastprox.dll because you are importing it?

**Comment by breed808** [comment]
> external PDB, we should have those PDBs somewhere if you are building with debugging enabled, to enable the symbols afaik

I've only been able to find aged sources for this, but it appears that Go [doesn't provide debugging symbols for Windows builds](https://stackoverflow.com/questions/17992425/debugging-go-golang-code-in-windows#17992540). Diving into these answers eventually links back to the [official Go documentation](https://go.dev/doc/gdb), which only mentions Windows in passing with Delve.

Building a new Windows binary in Go seems to confirm this, as the debugging symbols are automatically stripped (or were never available).

> @breed808 Based on the stack trace, you are connecting to WMI before you are logging anything, is this right?
Or is just loading the fastprox.dll because you are importing it?

There are [some](https://github.com/prometheus-community/windows_exporter/blob/c5ec339750c8739efd89bd14df11c528483e7f17/exporter.go#L304) [log](https://github.com/prometheus-community/windows_exporter/blob/c5ec339750c8739efd89bd14df11c528483e7f17/exporter.go#L308) [entries](https://github.com/prometheus-community/windows_exporter/blob/c5ec339750c8739efd89bd14df11c528483e7f17/exporter.go#L251) before the exporter connects to WMI.

**Comment by Sarkie** [comment]
So what I can see after doing an investigation, that once windows_exporter.exe connects to WMI via fastprox.dll it can hang with no input, control + c, nothing.

![image](https://user-images.githubusercontent.com/283203/181651502-419994ea-6aca-4549-b60c-332b29ddd07d.png)

What I then managed to do after lots of trying is rebuilding the WMI seemed to the be the fix here.

Hopefully that helps and maybe add to the Wiki, but all depends on where it hangs using ProcMon

```
net stop winmgmt /y

winmgmt /resetrepository
```

**Comment by gonchik** [comment]
Just curios, but I see builds include some pdb info
<img width="1348" alt="image" src="https://github.com/prometheus-community/windows_exporter/assets/12548235/ba9e88d1-ab29-405a-8ab3-ccb7578950a8">
