### ISSUE TITLE
Create official OCI image

### ISSUE THREAD

**Issue by stevehipwell** [prometheus-community/windows_exporter#1085]
Now that Microsoft has [changed the Windows container redistribution rights](https://techcommunity.microsoft.com/t5/containers/announcing-windows-container-base-image-redistribution-rights/ba-p/3645201) to allow Windows to be distributed outside of an organization it would be really useful if there was an official OCI image published at https://quay.io/organization/prometheus.

**Comment by breed808** [comment]
See https://github.com/prometheus-community/windows_exporter/pull/864#discussion_r748764267 for context when this was last discussed. I don't believe there's been anything further since then.

**Comment by stevehipwell** [comment]
@breed808 a lot has changed since the comments you've linked to; `WindowsHostProcessContainers` should be enabled in all supported K8s versions, there is plenty of builder & registry support for Windows & the aforementioned redistribution rights change. I can't see any technical blockers which is why I opened a new issue to see if it would be possible to get an image built.

**Comment by breed808** [comment]
Apologies, the link might not have opened the correct review comment in that PR.

> Hm, no, this is most likely something we'll need help from the main org owners to get done, and will require a bit of work in the CI bits. We've been running on AppVeyor (due to it historically being the only Windows-capable CI service), while the rest of the ecosystem builds on CircleCI. They do support Windows now, though, so we're not as starved for choice any more.
>
> Pinging @SuperQ - I recall you've been at least earlier been working on the CircleCI bits, any input on how to proceed here? Or is there anyone else that we should talk to?
The easiest for us would of course be to just get credentials that we can push to AppVeyor, but I'm not sure how we'd feel about spreading those, since I don't think they can be scoped to a single image path? Is a migration to CircleCI a requirement to get push access?

It's not a technical issue at this point; this project would need authorization to push to the main prometheus organization on Quay.

**Comment by breed808** [comment]
It's not actively been discussed since the comment I posted above.
I'll need to review the CI setup and see what's required to push to the official Quay repository.
