### ISSUE TITLE
netframework_clrmemory collector starts but metrics don't show in /metrics

### ISSUE THREAD

**Issue by suchendra-h** [prometheus-community/windows_exporter#1199]
Hi I'm pretty new to protheus, I am running windows_exporter v0.22.0 and prometheus v2.44.0-rc.0

here is my config.yml
```
---
# Note this is not an exhaustive list of all configuration values
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,textfile,netframework_clrmemory,process
collector:
  service:
    services-where: Name='windows_exporter'
  scheduled_task:
    include: /Microsoft/.+
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  path: /metrics
  max-requests: 5
web:
  listen-address: ":9182"
```
netframework_clrmemory collector starts and wmi queries succeed but windows_netframework_clrmemory_* metrics don't show in /metrics

any idea how I can troubleshoot this? am I missing something?

**Comment by breed808** [comment]
Assuming the issue is still occurring, you can [query the WMI class](https://learn.microsoft.com/en-us/windows/win32/wmisdk/retrieving-a-class) to see if Windows is providing any metrics to the collector.

The class in question is [Win32_PerfRawData_NETFramework_NETCLRMemory ](https://github.com/prometheus-community/windows_exporter/blob/e0e31254e2b352522e1098f6796f3a57a4df6081/collector/netframework_clrmemory.go#L120).
