### ISSUE TITLE
v0.23.0/v0.23.1 - Windows service can't stop without an error

### ISSUE THREAD

**Issue by kago-dk** [prometheus-community/windows_exporter#1258]
When I try to stop the windows_exporter service (v0.23.0/v0.23.1), it always returns an error:
<img width="401" alt="image" src="https://github.com/prometheus-community/windows_exporter/assets/49529296/a210e083-3b51-4dcf-98bc-c6a1821b5836">

The event viewer does not provide a lot of details
_"The windows_exporter service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 60000 milliseconds: Restart the service."_

* I have tried windows_exporter-0.23.1-amd64.msi (to rule out a configuration issue on my part) and windows_exporter-0.23.1-amd64.exe, and both approaches produce the same problem.
* I have tried with config.yml (my existing setup using windows_exporter-0.23.1-amd64.exe) and without config.yml (as windows_exporter-0.23.1-amd64.msi does), and both approaches produce the same problem.

windows_exporter-0.22.0-amd64.msi does not have a similar issue.

**Comment by kago-dk** [comment]
Am I the only one seeing this issue?

**Comment by DiniFarb** [comment]
This might be cos the svc is handled in a separate routine with the ini() function. Let me explain what I think:

The communication between the exe and windows happens in the `initiate.go` file strictly speaking in this function: 

https://github.com/prometheus-community/windows_exporter/blob/8d615956074d9329eb33ece5ec19fc00a8d2af48/initiate/initiate.go#L22-L43

So if the windows service is stopped the case `case svc.Stop, svc.Shutdown:` will take place. Send a stop signal to the main thread with `s.stopCh <- true` then break the loop and send a signal back to windows that it is about to stop, with `changes <- svc.Status{State: svc.StopPending}`. But this might never happen, if the main process ends very quickly after `s.stopCh <- true` the `changes <- svc.Status{State: svc.StopPending}` will never be reached cos the main process does not wait for finishing any subroutines. This is a matter of µs cos in the main thread after the stop is received only one message is logged:
https://github.com/prometheus-community/windows_exporter/blob/8d615956074d9329eb33ece5ec19fc00a8d2af48/exporter.go#L307-L312

So maybe it all comes down in how long it takes to log the stop massage and if that amount of time is enough to hold the exe alive to send the `changes <- svc.Status{State: svc.StopPending}` 😄 And since in v23 there was a switch to a new logger( https://github.com/prometheus-community/windows_exporter/commit/8509bc69a60bb6b608d390fabdf6e4d64b939b2e ) lib this might was enough to end the process a bit quicker and miss sometimes the to send that signal back to windows.

This would also explain the error since windows sent a stop signal but did not receive any signal back so it just assumes the process died unexpectedly. 

I think this could be easily fixed if the `changes <- svc.Status{State: svc.StopPending}` would be moved before the `s.stopCh <- true` 

@breed808 I could try it and create a PR?

**Comment by breed808** [comment]
> @breed808 I could try it and create a PR?

Yes please!
