### ISSUE TITLE
unable to pull the image on windows or linux machines

### ISSUE THREAD

**Issue by zrankinOCEUS** [prometheus-community/windows_exporter#1363]
Hello, I'm attempting to pull the image as part of the kube-prometheus-stack, but I am unable to pull the windows exporter on linux and windows machines. 

I first attempted to pull the image on a linux machine without much thought and was met with the following error: 

`latest: Pulling from prometheus-community/windows-exporter
no matching manifest for linux/amd64 in the manifest list entries`  

I tried again using docker on windows but was met with the same error. 

I've tried numerous hack-y solutions while attempting to pull this image but none are successful. Is there an auth requirement for this image?

**Comment by zrankinOCEUS** [comment]
Thanks for the suggestion! 

I ended up changing the call for the windows-exporter to an empty image I pushed to a private repository since I wasn't using the windows exporter. 

I'll be sure to give this a whirl. 

> Try with the OS/Arch tab:
> 
> ![image](https://private-user-images.githubusercontent.com/74785136/297019784-a0bae756-6546-4ed3-a575-91f1000bad0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MjU1NTAsIm5iZiI6MTcwNTQyNTI1MCwicGF0aCI6Ii83NDc4NTEzNi8yOTcwMTk3ODQtYTBiYWU3NTYtNjU0Ni00ZWQzLWE1NzUtOTFmMTAwMGJhZDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE3MTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YmE5Y2ViZDg4MjQ3YWQ2ZjczY2IzNTEwNjAwYzI4NTc0M2ZmZWYyYmZiZGU0NmQwODI2MjFlN2NhYzg1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JQ4Qj7k19m3CmOAsVBFaIqaxKwCKhSHdOe--7dEmGSU)

**Comment by jkroepke** [comment]
HI,

this expected that you can not pull the image on linux, since its an windows exclusive image.

What the error message on your windows nodes?

Please note that Docker for Windows, refer [docs](https://docs.docker.com/desktop/faqs/windowsfaqs/#how-do-i-switch-between-windows-and-linux-containers) to switch to Windows Container first before loading the image.


In case you try to sync the image to an private registry, you should use other tools instead do `docker pull/tag/push`. For example skopeo or crane.
