### ISSUE TITLE
textfile_dir not inst

### ISSUE THREAD

**Issue by irnmn** [prometheus-community/windows_exporter#1382]
use command msiexec /i windows_exporter-0.25.0-amd64.msi ENABLED_COLLECTORS="cpu,cs,iis,logical_disk,memory,net,os,process,scheduled_task,service,system,tcp,textfile" LISTEN_PORT="9182" TEXTFILE_DIR="C:\custom_metrics\" freezing process in progress
But if you run without the last command, then everything is successful

**Comment by DiniFarb** [comment]
This my fault, because as I was implementing #1262 (v0.24.0) I forgot to update the wxs https://github.com/prometheus-community/windows_exporter/blob/6ede10e29aeea4e5aa250a20ade395ce14058fdc/installer/windows_exporter.wxs#L47-L48

With  #1262 the flag `--collector.textfile.directory` was marked deprecated and then in the next release removed by #1337 (v0.25.0)

@breed808 should I bump in a PR to fix? If so my question would be, should I also update the ID like `Id="TEXTFILE_DIRS"` instead of `Id="TEXTFILE_DIR"`

**Comment by breed808** [comment]
Yes please, a PR is welcome. I'd go with `Id="TEXTFILE_DIRS"` as that clearly indicates that multiple directories can be supplied. The `TEXTFILE_DIR` reference in the main README will need to be updated too.

**Comment by irnmn** [comment]
will there be a new version 0.25.1 or what?

**Comment by jkroepke** [comment]
https://github.com/prometheus-community/windows_exporter/releases/tag/v0.25.1 - please let us know, if you issue is resolved

**Comment by eklunko** [comment]
> The `TEXTFILE_DIR` reference in the main README will need to be updated too.

Possibly the `Description` cell for TEXTFILE_DIRS in the main README needs to be updated too.
