### ISSUE TITLE
tcp collector

### ISSUE THREAD

**Issue by kobid84** [prometheus-community/windows_exporter#1577]
### Problem Statement

i'm not able to monitor live data of failure or reset connection - only total data
also missing ability to monitor tcp TIME_WAIT connections at all

### Proposed Solution

- implement **windows_tcp_connections_reset** as gauge
- implement **windows_tcp_connections_failures** as gauge
- implement **TIME_WAIT** connections

**Comment by jkroepke** [comment]
Whats the use-case to change the metric to gauge, if it's an counter?

**Comment by DiniFarb** [comment]
Yeah we had once a similar issue where we needed to check a process which did create many tcp connections. We used the textfile collector for a while to scrape the tcp connections for that specific process. 

But there is disclaimer, it really depends on how long the tcp connection is active and in what cycles Prometheus scrapes the exporter - In our case this worked because the process in question created many long standing tcp connections to one endpoint around 60-90s in Established mode and our Prometheus scraped every 30s. We did this because we needed to send alerts for this process before it reached its tcp connection limit.
There is a good chance tough that you miss many connections depending how long the connection is active. If you scrape every 30s, there is a good chance that in between a tcp connection is opened and closed and with a gauge you miss the value. So in my opinion it does really make sense to create gauges. Maybe only for some edge cases like mine, but then the textfile collector is really the best option.

@kobid84 If you want I can share the ps1 script we used to create the prom file for the textfile collector. It can easily be modified to scrape all `TIME_WAIT` tcp connections. Just keep in mind that you only get a good result if you scrape the exporter in very short cycles.

**Comment by kobid84** [comment]
hi
yes! it will be great if you can share the ps1 script file

**Comment by jkroepke** [comment]
Feel free to continue to discuss, but I guess I cant help here.

**Comment by DiniFarb** [comment]
@kobid84 

We used this script which was started by a windows task (at startup). 

```ps1
$workingDir = (pwd).Path
$tempFile = $workingDir + "\temp-tcp.txt"
$promFile = $workingDir + "\tcp.prom"
$errorMessage = $workingDir + "\error-tcp.txt"

while ($true) {
    try {
        $result = @{}
        #Might filter for specific process like this:
        #$connections = Get-NetTcpConnection -OwningProcess <ID> -ErrorAction Stop
        $connections = Get-NetTcpConnection -ErrorAction Stop
        foreach ($c in $connections) {        
            $metricString = "tcp_connections{process=`"$($pName)`",state=`"$($c.State)`",remote_port=`"$($c.RemotePort)`",remote_addr=`"$($c.RemoteAddress)`"}"
            if ($result.ContainsKey($metricString)) {
                $result[$metricString] += 1
            }
            else {
                $result.Add($metricString, 1)
            }
        }
        Set-Content -Path $tempFile -Encoding Ascii -NoNewline -Value ""
        Add-Content -Path $tempFile -Encoding Ascii -NoNewline -Value "# HELP current tcp_connections`n"
        Add-Content -Path $tempFile -Encoding Ascii -NoNewline -Value "# TYPE tcp_connections gauge`n"
        foreach ($r in $result.GetEnumerator()) {
            Add-Content -Path $tempFile -Encoding Ascii -NoNewline -Value "$($r.Name) $($r.Value)`n"
        }
        Move-Item -Path $tempFile -Destination $promFile -Force
        Start-Sleep -Seconds 10
    }
    catch {
        Set-Content -Path $errorMessage -Value $_
        break;
    }
}
```
