### ISSUE TITLE
Ability to drop certain metrics?

### ISSUE THREAD

**Issue by poblahblahblah** [prometheus-community/windows_exporter#213]
Is there a way, via configuration, to not have certain metrics passed along on scrape time? In our largest data center the CPU CSTATE metric(s) creates about 180,000 unique data points. We definitely want the CPU usage, but unfortunately the CSTATE information is not all that valuable for us so we would like to just turn it off.

We can do this in our Prometheus config, but it is not recommended to drop metrics long term.

**Comment by avonwyss** [comment]
@poblahblahblah What's the problem with doing it via metric relabeling? You can have these dropped before they are stored in Prometheus. The only drawback I see is slightly more resource usage for rendering, transferring and parsing the CSTATE information upon scrape, but I think this should be pretty much irrelevant.

**Comment by poblahblahblah** [comment]
@avonwyss Just trying to follow best practices according to https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus/

> All the samples are still pulled from the job being scraped, so this should only be a temporary solution until you can push a fixed version of your code.

**Comment by poblahblahblah** [comment]
I suppose another question is - if I create a PR to breakout the CSTATE information into a separate collector, would that PR be considered?

**Comment by carlpett** [comment]
Hi @poblahblahblah,
I believe what @brian-brazil is referring to in that blog post is that "fixing" your code rather than dropping metrics is a workaround for your own instrumented applications when something generates a lot more metrics than expected. In this case, the exporter is working as expected, so dropping metrics you are not interested in would be ok, even as a long-term situation (feel free to correct me if this is not how you meant it, Brian)
Regarding changing the behaviour, we might consider a PR that adds a flag to disable collecting these specific metrics (say something like bool flag `--collector.cpu.collect-cstate`, that'd also create a `--collector.cpu.no-collect-cstate` which is what you want).
I'm somewhat interested in the volume problem though - you're getting three points per core, right? Is that a significant portion of your total metric volume?

**Comment by poblahblahblah** [comment]
> In this case, the exporter is working as expected, so dropping metrics you are not interested in would be ok, even as a long-term situation (feel free to correct me if this is not how you meant it, Brian)

OK - it wasn't immediately clear to me that the advice strictly applied to our application code. I guess I treated the "so this should only be a temporary solution..." more as gospel than I should have.

> Regarding changing the behaviour, we might consider a PR that adds a flag to disable collecting these specific metrics (say something like bool flag --collector.cpu.collect-cstate, that'd also create a --collector.cpu.no-collect-cstate which is what you want).

I'll look at getting a PR going for this, but with the above information in mind I'll probably just drop the metrics.

> I'm somewhat interested in the volume problem though - you're getting three points per core, right? Is that a significant portion of your total metric volume?

I guess it depends on what you consider significant - In our largest colo we are currently collecting ~925,000 system metrics with wmi_collector. CSTATE metrics account for about 180,000 of those, so rounding down we're at 19% of the metrics are for CSTATEs, which we likely don't need.

**Comment by carlpett** [comment]
I'll leave this open as a feature request, and if someone else feels a need to disable cstate metrics we'd welcome a PR to do this.
