### ISSUE TITLE
Feature request: WCF Performance metrics for ServiceModelEndpoint 4.0.0.0 and ServiceModelOperation 4.0.0.0 Calls Per Second, Calls Duration and Calls Outstanding

### ISSUE THREAD

**Issue by harrywer** [prometheus-community/windows_exporter#218]
Expose the metrics of ServiceModelEndpoint 4.0.0.0 and ServiceModelOperation 4.0.0.0 Calls Per Second, Calls Duration and Calls Outstanding.

**Comment by stojy** [comment]
Anyone have any thoughts on how difficult this might be?  Or whether there's a (better) alternative?

**Comment by carlpett** [comment]
Hopefully not very hard :) There's both a tool for generating most of the code, and we try to give helpful reviews of work-in-progress as well if you want or need it.

**Comment by stojy** [comment]
In that case since it's not very hard ;)  I'd **really** appreciate seeing the WCF metrics added.

Combined with the other useful WMI metrics that are already published, inluding the WCF metrics would give us a great insight on what's going on in our WCF applications running on our servers via prometheus/grafana.  And best of all, I wouldn't need to fire up perfmon anymore!
