### ISSUE TITLE
Run wmi_exporter as a docker container

### ISSUE THREAD

**Issue by patrick-motard** [prometheus-community/windows_exporter#268]
I'm looking to use wmi_exporter in a hybrid swarm (windows and linux nodes, linux managers). I have used [Swarmprom](https://github.com/stefanprodan/swarmprom) successfully to monitor linux nodes in the swarm. In swarmprom the node_exporter (linux equivalent to wmi_exporter) is deployed as a docker container to all the linux workers. 

Would it be possible to do the same with wmi_exporter or does this solution have to be deployed on the host as a windows service?

**Comment by carlpett** [comment]
I still haven't found the time to experiment with how WMI and Docker interact (or check for actual Docker-related WMI classes), sadly.
Deploying directly will definitely work, of course, but as for running containerized, it is still unknown.

**Comment by pascalberger** [comment]
@patrick-motard @carlpett Were you successful with running the exporter as a docker container?

**Comment by carlpett** [comment]
There's a bunch of other issues where this has discussed more recently and which has more detail, so I think I'll close this one. 
But the short of it is "yes but no". It starts up fine and produces metrics, but the metrics are not from the host machine, but the container instance. This is a limitation of the Windows container implementation, rather than the exporter.
