### ISSUE TITLE
Docker container metrics usable on 1803?

### ISSUE THREAD

**Issue by semaph0r** [prometheus-community/windows_exporter#338]
Currently I am struggling with running WMI exporter with container collector on Windows Server 1803 SAC.

The service can be installed via `msiexec`, with container as additional collector. But starting the service will give me error code 8 (Not enough memory).

Installing the wmi_exporter without any collectors specified works well.

Are there any problems reported regarding the WMI interfacing on 1803?

**Comment by carlpett** [comment]
Hi @semaph0r,
That's nothing we've heard about so far, no, but the container collector is fairly new, and Windows container support too, so there are likely scenarios that haven't been tested yet. Perhaps @sachinmsft has any insights?
I'm guessing the error is actually some generic "cannot allocate" thing, rather than memory specifically. So, continuing my guessing, it could be some sort of permission issue, or some resource which is not ready to be used. Does the container support in general seem to work? No pending restarts?

**Comment by sachinmsft** [comment]
I can test on this build and will confirm if it has any issues. 
@semaph0r were you able to get the container metrics on other builds ?

**Comment by semaph0r** [comment]
Hi @sachinmsft,
on my local machine build 1809 is running and I was capable of getting metrics for running windows containers. But the `wmi_containers_count` is off by one. Just one container is running, thus the metric is set to 2.

Any further questions?

**Comment by sachinmsft** [comment]
docker creates an extra pause container to create the isolated environment for container to run.
that the reason you are seeing wmi_containers_count 2.
