### ISSUE TITLE
Get process id for .NET CLR Exceptions

### ISSUE THREAD

**Issue by VoidMonk** [prometheus-community/windows_exporter#346]
Hi guys, currently the [.NET CLR Exceptions collector](https://github.com/martinlindhe/wmi_exporter/blob/master/collector/netframework_clrexceptions.go) gets the metrics and their process name(s).

For IIS `w3wp` processes, the name comes back as w3wp, w3wp#1, w3wp#2 etc. so it's impossible to figure out which exact worker process or AppPool are the metrics for.

Is it possible to get the process id or AppPool name in the collector, much like the Process and IIS collectors?

Thanks.

**Comment by carlpett** [comment]
Hi @VoidMonk,
Yes, it should be possible to do the same exercise for mapping them up as in the process collector: https://github.com/martinlindhe/wmi_exporter/blob/462a136673af7337a67df98b8ed578db4dfeb06b/collector/process.go#L194-L215

**Comment by VoidMonk** [comment]
Thank you @carlpett. It'll be great if this can be merged in `netframework_clrexceptions.go` as well, or better if this was a global function (if there's such a thing in go lang), that could then be called by other collectors. I would've submitted a PR but I don't program in go, so I don't have it setup for dev/testing.

**Comment by PureCognition** [comment]
This issue is a couple years old and is still open.  I'm running into this exact same problem when monitoring CLR metrics in Windows Server Core.  Is there a reason that it hasn't been implemented yet?  Is there a good workaround that I'm not aware of?  Most of the articles I've read for getting the App Pool or Process ID from the w3wp#N ID involves doing things that aren't really possible in Windows Server Core, to my knowledge.  And, even if they were possible, that's a huge pain in the butt.

**Comment by breed808** [comment]
>  Is there a reason that it hasn't been implemented yet? 

I can't speak for others, but I've had no need to monitoring CLR metrics so far. So I've not had much to do with this particular collector.

If you're able to resolve the issue yourself, or know someone who has, we'd happily welcome a pull request to resolve the issue.
