### ISSUE TITLE
WMI-Exporter starts but is not reachable

### ISSUE THREAD

**Issue by sekekec** [prometheus-community/windows_exporter#381]
Hi,

i've configured WMI as a service on a windows host and can start it without errors. After that i can see that the port is listening but i can not get any response by open it via browser.

Starting the service with the same service user via console works without any problems. 

After making the service user to a local admin the service runs and responds. There must be a right or policy issue i think.

Is there a set of rights and policies the service user must own?

**Comment by carlpett** [comment]
Hi,
Due to how Windows restricts access to WMI, the service needs a very extensive set of permissions. Basically, it does not work very well without having full admin access.
This isn't great, but to the best of our knowledge, it isn't possible to avoid. If you were to find a way to configure a service account such that it is meaningfully less privileged, we'd be very interested to know!
