### ISSUE TITLE
All collectors failing except CPU - only on 2 nodes

### ISSUE THREAD

**Issue by allthegoodnamesaretaken** [prometheus-community/windows_exporter#422]
Hello, I hope this finds you well.

We're using wmi_exporter across all our windows nodes, (v0.8.3) and all of them seem to behave properly, except one cluster with 2 nodes. On both machines, of all the collectors we have enabled (os,memory,cpu,net,tcp,process,service,system,cs,logical_disk,mssql), only CPU seems to succeed and report any data, 

$ curl http://myHost:9182/metrics | grep wmi_exporter_collector_success
wmi_exporter_collector_success{collector="cpu"} 1
wmi_exporter_collector_success{collector="cs"} 0
wmi_exporter_collector_success{collector="logical_disk"} 0
wmi_exporter_collector_success{collector="memory"} 0
wmi_exporter_collector_success{collector="mssql"} 0
wmi_exporter_collector_success{collector="net"} 0
wmi_exporter_collector_success{collector="os"} 0
wmi_exporter_collector_success{collector="process"} 0
wmi_exporter_collector_success{collector="service"} 0
wmi_exporter_collector_success{collector="system"} 0
wmi_exporter_collector_success{collector="tcp"} 0

The logs also show several errors every few minutes (samples below), but none really indicate what the root problem is. Since it's only happening on these 2 nodes, i suspect it's a problem with the way they're setup, or some other environmental issue, but i can't figure out what it could be. Can you please give any advice or direction?

Sample logs:
- mssql class collector memmgr failed after 0.236518s: Exception occurred. (The object invoked has disconnected from its clients. )
- ERROR 102 failed collecting tcp metrics:<nil> Exception occurred. (The object invoked has disconnected from its clients. )
- failed collecting memory metrics:<nil> Exception occurred. (The object invoked has disconnected from its clients. )

**Comment by carlpett** [comment]
Hi @allthegoodnamesaretaken,
Sorry for taking so long to get back to you! I would guess that there is an issue with how WMI is working on these machines. On the version you are running, the CPU collector is the only one using the new perflib code (a lower-level interface to the performance counters, which we are migrating most collectors to), so that it is the only one succeeding while all the WMI-based ones fail indicates WMI having issues.
If this is still a problem, could you try running `Get-WMIObject Win32_ComputerSystem` in a Powershell terminal? This would tell us if the problem is with all users of WMI, or only our calls.

**Comment by breed808** [comment]
Closing due to a lack of activity
