### ISSUE TITLE
WMI throws many timeouts (event viewer)

### ISSUE THREAD

**Issue by rong0312** [prometheus-community/windows_exporter#447]
Hey all,
I have installed WMI on my windows server 2012R2 with the following flags:
`ENABLED_COLLECTORS=os,iis,logical_disk,process,net` 
My problem is that I am getting a lot of timeouts from the WMI service as you can see (event-viewer):  

![Screen Shot 2019-12-18 at 16 07 50](https://user-images.githubusercontent.com/33253167/71094735-206bff80-21b4-11ea-8a1c-02290e13dd7c.png)

Did anyone face this issue? if so how can I resolve this?

**Comment by carlpett** [comment]
Hi @rong0312,
This could have several reasons. Some questions to help narrow it down:
- Is the machine running under heavy load, CPU-wise? That is known to cause WMI queries to take a long time.
- What is your scrape timeout configuration in Prometheus? The wmi_exporter will try to return _something_ before Prometheus times out, even if not all collectors have finished yet.
- Do you have similar machines where this does not happen?

**Comment by rafimees** [comment]
Hi,
the scrape time is 5s
when we installed the exporter on windows servers with the default msi install then on machines with light load there were no issues. but once we installed the exporter on IIS machines with high CPU 
ENABLED_COLLECTORS=os,iis,logical_disk,process,net
load errors started showing in the event log

**Comment by carlpett** [comment]
Hi @rafimees,
Do you work with @rong0312, or is this a similar report from another organization?
With scrape time 5s, you mean the scrape interval, correct? Do note that such a low interval will add a not-insignificant load to your machines, and you might want to think about what you gain with such high resolution vs the costs.
But what I meant was the scrape *timeout*, which is how long Prometheus allows the request to take before aborting and marking the target as down. By default this is 10s. 

If your machines are already running at high load, doing several WMI queries every 5 seconds will likely mean that they will many times not complete before the next 5 seconds comes with new queries, etc etc. So there really isn't a "solution" to this - WMI isn't fast enough to sustain 5 second intervals when the machine is too heavily loaded to respond to them. 
_(Incidentally, this is the reason we are moving as many collectors as possible over to using perflib, since this will reduce the required resources to produce the metrics. But there is still lots to do, and some parts do not seem to be possible to query with perflib)_

**Comment by rafimees** [comment]
Hi, @carlpett, i do work with ron.
where do i see the  scrape timeout in prometheus setting
is perflib part of a prometheus solution?

**Comment by carlpett** [comment]
It is configured in the `scrape_config`, like the interval. If you don't set it, the default is 10 seconds.
The perflib migration is being done in this exporter, and as of v0.9 the cpu, logical_disk, memory, net and system collectors are using perflib rather than WMI (WMI is itself a high-level interface on top of perflib).
So from your list, the iis and process collectors are still using the slower/resource intensive methods. Hopefully we have time to migrate them too in the near future.

To get back to the topic of the issue, though. I think there's a clear explanation already about *why* the timeouts happen, so to discuss what you can do configuration-wise to reduce the impact instead:
- Prometheus config: Increase the scrape interval from 5s to say 30s or even 60s
- Prometheus config: Increase the scrape timeout, while still keeping it shorter than the scrape interval
- Exporter config: Ensure you have filters on the process collector (`--collector.process.processes-where`), to reduce the amount of data fetched
- Infrastructure/deployment: Move workloads around on your machines to keep CPU load manageable (I realize this might not be easy)

**Comment by cedric-ca** [comment]
Hi,

We do encounter the same problem.
wmi_exporter: 0.13.0 amd64
Server: Windows Server 2012 R2 Standard
ENABLED_COLLECTORS=cpu,os,logical_disk,process,system
It stuck with: Event ID 101 Collection timed out, still waiting for [os process]

After further investigation, I found that there is a WMI-Activity Error: Event ID 5858 with ResultCode 0x80041032.
After a quit search I found this solution from microsoft: https://docs.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/wmi-activity-event-5858-logged-with-resultcode-0x80041032

Could you check the way you use IEnumWbemClassObject::Next?

Thanks

**Comment by carlpett** [comment]
Hi @cedric-ca,
From a quick read, I believe that event is something of a false alarm here. If we detect a collector has timed out, we won't actually bother to read all the results that come back too late. So the event would be expected in this case, and is a symptom rather than a cause.
