### ISSUE TITLE
Latency data from logical_disk collector seems to be wrong

### ISSUE THREAD

**Issue by AntonSmolkov** [prometheus-community/windows_exporter#462]
Hi. Can't find any corellation between data gathered from perfmon.exe and collected with wmi_exporter.
For the same periond (15 minitues) data looks completely different.
If i understand right, at least average data must be the same.

**Perfmon.exe counters:**
LogicalDisk -> Avg. Disk sec/**Read**. 
Result AVG - **0.023 seconds**

LogicalDisk -> Avg. Disk sec/**Write**. 
Result AVG - **0.031 seconds**

**Wmi_exporter counters:**
rate(wmi_logical_disk_**read**_seconds_total)[60s]
Result AVG - **1.76 seconds**

rate(wmi_logical_disk_**write**_seconds_total)[60s]
Result AVG - **3.41 seconds**

<details><summary>Pictures</summary>

![изображение](https://user-images.githubusercontent.com/5318028/74419115-78448100-4e5a-11ea-8a45-3671bed13a6b.png)

![изображение](https://user-images.githubusercontent.com/5318028/74419519-16384b80-4e5b-11ea-9699-f9f55ad1a7f3.png)

</details>

wmi_exporter version - 0.9.0
scrape_interval - 15s

**Comment by AntonSmolkov** [comment]
@breed808 Please have a look.

**Comment by breed808** [comment]
Hi @AntonSmolkov, I've not been able to reproduce the inconsistency on my personal device.
I'll check one of our servers tomorrow and look for a difference in metrics.

**Comment by AntonSmolkov** [comment]
Thank for having a look. In my opinion this metric is the one of the most important system metrics at all.

Original testing was made on windows server 2016. Just in case i've also tested on 2012r2 and had the same result.  
BTW, look at the max write latency, it's 23 seconds, i guess that is impossible result. 
Sometime i could even face results above 60s under high IO pressure, which looks impossible too.

**Comment by breed808** [comment]
I've had a closer look at these metrics on our file server; I think the issue is partly due to the calculation of the average.
The Performance Monitor is sampling the underlying counter every few seconds, and the average presented to the user is the average for the duration (15min 2sec from your screenshot?). This would be equivalent to `rate(wmi_logical_disk_read_seconds_total[902s])`. Note that the averages would not exactly match due to differences in the Perfmon and Prometheus sampling rates.

I've demonstrated this with two graphs, one showing the instant value for `rate(wmi_logical_disk_read_seconds_total)[1m])`, the other displaying the same query graphed over time. The instant query (0.049) is closer to the average presented by perfmon (0.004) than your metrics, but is still 10x higher than the average reported by Perfmon.

![latency_graphs](https://user-images.githubusercontent.com/3103817/74727226-c5e53300-5238-11ea-89be-013a72d36ccb.png)

Can you check your Perfmon averages against an instant query or viewing the `current` value in your graph and see if the difference in averages is reduced? I feel some Microsoft documentation on Perfmon's processing of the underlying counter would be welcome.

**Comment by zakiharis** [comment]
Hey there,

Sorry, I'm late by a year. 

I'm also noticing a huge difference in the latency data.

--

I'm using windows_exporter 0.14.0 and this Windows Server is a VM hosted in VMware. Below is the metric from windows exporter.

![1](https://user-images.githubusercontent.com/1005824/110267953-c85d2b00-7ffb-11eb-8b90-505270d02a67.png)

Below is the metric from VMware vSphere

![2](https://user-images.githubusercontent.com/1005824/110268185-3a357480-7ffc-11eb-8027-925548829fdf.png)

and below is the metric from vRealize Operations (vROps)

![3](https://user-images.githubusercontent.com/1005824/110268289-62bd6e80-7ffc-11eb-8faf-4f6bffd8d5fc.png)


sorry to tagged you guys

@AntonSmolkov is your issue with latency resolve?
@breed808 @carlpett please let me know if you guys have info about this ya

thank you

**Comment by AntonSmolkov** [comment]
Hi, @zakiharis. No, i haven’t managed to resolve it. Had to replace wmi_exporter with telegraf. Satisfied so far
Take a look - https://grafana.com/grafana/dashboards/3563
It is kind of more plain (gauges instead of counters), but does it’s job.
