### ISSUE TITLE
Same name and label value error results in no Prometheus format data

### ISSUE THREAD

**Issue by da77a** [prometheus-community/windows_exporter#466]
I encountered this problem with the "net" collector failing but others have reported similar issues with other collectors see #271 #272 #379 ... 

I believe the problem started after some combination of system sleep and/or swapping identical (USB) network adapters when hotdesking.

Aside from why/how the collector is failing, the error handling results in a non-Prometheus response. It would be better if the failure did not "bail out" of running other collectors and if errors were reported as prometheus metrics  as suggested https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes - which is the case for some errors - just not this one. Even better would be if only the metrics that "collided" were dropped, not all metrics from the collector.

The result I receive is [metrics.txt](https://github.com/martinlindhe/wmi_exporter/files/4218220/metrics.txt)

I tried the approaches suggested in #379 to clear wmi with no success. Powershell wmi query is returning reasonable results (no duplicate) [wmi.txt](https://github.com/martinlindhe/wmi_exporter/files/4218232/wmi.txt)

If I run just one collector (not net) I get results. If I run any set of collectors that includes the failing net collector, I get just the net failure report, no metrics.

**Comment by da77a** [comment]
I see that PR #274 (which was text collector specific) and "masked" failures was not accepted... So only a PR that fixed root cause (which nobody seems to have pinned down) across all metrics/collectors that have cause this (at least 3) would be accepted? For my use not going blind on all metrics due to one failed (dup) metric seems lesser evil than current complete failure to deliver any metric (and instead deliver a result that is neither valid Prometheus nor a HTTP 500 to indicate that the scrape has failed and is likely to continue failing, and there is no valid Prometheus data to deliver).

**Comment by carlpett** [comment]
HI @da77a,
To some extent this is expected, as you can read in the comments on that PR. The main problem is that we currently do not have a good way to detect errors while reading the data, only after it is aggregated is it possible to see that it is invalid. And when it is aggregated, that means we fail the entire scrape, as you notice. The "best" scenario here would be for us to gain the capability of detecting the bad data early, and then just fail the specific collector.
It's been a while since I took a look at this last time, and maybe we could find a way now. However, it isn't a trivial thing, so I wouldn't count on it to solve any immediate pressing issues. How often are you running into this?
