### ISSUE TITLE
No netframework_clrmemory metric in AWS EC2

### ISSUE THREAD

**Issue by vkarmendra** [prometheus-community/windows_exporter#481]
Hi there,

I have an AWS EC2 machine where I have installed wmi_exporter-0.10.2-386.msi using below script

msiexec /i wmi_exporter-0.10.2-386.msi ENABLED_COLLECTORS="cpu,iis,memory,process,netframework_clrmemory,net"

but when I am fetching the metrics, its not providing netfamework_clrmemory metrics. I have a lot of websites running in IIS over there.

Though I am getting below metrics which shows collection of netframework_clrmemory is successful.

wmi_exporter_collector_duration_seconds{collector="netframework_clrmemory"} 0.1386299
wmi_exporter_collector_success{collector="netframework_clrmemory"} 1

Please let me know if there is anything I missed.

**Comment by AbsorbJonny** [comment]
My company also has this issue.  We've installed collectors on multiple EC2 machines and always get this same result.  On a local developer machine it works, but on an Amazon EC2 instance it doesn't.  We're running the latest release, v0.10.2.

In PowerShell we directly ran "Get-WmiObject Win32_PerfRawData_NETFramework_NETCLRMemory" and get results back.  Then we install the exporter.  After the exporter is installed when we run this command we no longer get results.  Then we uninstall the exporter and try running it again, but we no longer get results from this PowerShell command.  Something about the exporter seems to be breaking this functionality.

**Comment by carlpett** [comment]
@vkarmendra
Do you get any results when running `Get-WmiObject Win32_PerfRawData_NETFramework_NETCLRMemory`? Do get results if using `perfmon`?
Also, while I do not think it is related, is there a reason you use the 32-bit installer?

@AbsorbJonny,
That sounds very unexpected. The exporter is pretty much doing what you are doing in that Powershell query, and that's all... Are you seeing that behaviour anywhere else than on Amazon? I'm not aware of any difference in how Windows works on EC2 on this low level, but I suppose there could be something. Do you get any event logs?
Are you also running on 32-bits, by the way?

**Comment by AbsorbJonny** [comment]
We've just stared experimenting with the exporter in our production environment so haven't seen this elsewhere as this is the first implementation.

As for event logs, I see messages of this nature in the logs:

"Collection timed out, still waiting for [process netframework_clrmemory netframework_clrlocksandthreads netframework_clrexceptions cs iis]"

Meanwhile, the metrics returned from the collector show "wmi_exporter_collector_success" always reports "1" for all metric sources, and "wmi_exporter_collector_timeout" always reports "0" for all sources.  I see no missing output for any metric other than the .NET based metrics, "cpu,cs,iis,process,logical_disk" all seem to work okay.

I checked with our IT people and it turns out they did install the 32 bit version of the collector rather than the 64 bit version.  I had been testing with the 64 bit version and had no issues in my local DEV environment.  I have requested that they install the 64 bit version and will let you know what happens.  We're running Windows Server 2016, by the way.
