### ISSUE TITLE
Collect data from remote computer

### ISSUE THREAD

**Issue by FreddieAkeroyd** [prometheus-community/windows_exporter#510]
Hi, how would it be best to collect data from a remote computer? I see that wmi.Query() can accept  connectServerArgs to specify these details, is that the best approach or is there another option available? Thanks, Freddie.

**Comment by carlpett** [comment]
HI @FreddieAkeroyd,
The Prometheus ecosystem strongly favours local collection to avoid another network hop introducing another possible error source, so this is not something we will support.
Additionally, we mainly use Performance Counters instead of WMI these days (a name change to reflect this is under discussion in #499), which are not possible to collect remotely, so you wouldn't be able to read much data.
Is there a reason you cannot install the exporter directly on the target system?

**Comment by FreddieAkeroyd** [comment]
Hi @carlpett we currently use a rather old nagios system with check_wmi_plus to obtain metrics, the computer manager of the systems we are monitoring prefers not to install additional software on them for stability reasons which is why I was investigating the option of remote monitoring. We are not currently using Prometheus, I am investigating what options we may have at the moment for updating/changing our system. I guess I could still use a version of check_wmi_plus and send metrics into a Pushgateway if I am unable to run a wmi_exporter instance locally?

**Comment by carlpett** [comment]
Technically you can build a setup with pushgateway, but there are a number of gotchas that makes this an option you won't see recommended. See the [Prometheus docs](https://prometheus.io/docs/practices/pushing/) for some general things to look out for. If you have no other choice, take care to ensure you know how it behaves in different scenarios, eg when the host is down, or some series disappear but not others.

**Comment by Mario-Hofstaetter** [comment]
@FreddieAkeroyd Another possibility, while not pretty, is to use the [`textfile collector`](https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.textfile.md) instead.

- Install wmi_exporter on any machine you have control over and scrape it, `textfile collector` is on per default
- Get your metrics in prometheus format into `.prom` files into your `collector.textfile.directory`
- Use any means at your disposal to get your metrics, convert the output of `check_wmi_plus` to prometheus format, use **powershell remoting** to connect to your targets if possible, etc.
- Provide labels containing the host information of your remote computers

Cons:
- You have to write the scripts and convert the data yourself, the prometheus format is very simple though
- You loose automatic down detection via `up` metric, since this one wmi_exporter is always up
- This exporter becomes a single point of failure, if it goes down all monitored instances are in the blind

Pros:
- You can do ANYTHING you want or need, as long as you can script or program it
- You can always roll your own `up` metric if needed. If you want to use the default labels (e.g. `instance`) you would have to use [`honor_labels` I think](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config)

There are many things to monitor that are not supported by any default collector / exporter. I am currently writing powershell scripts to monitor:
- Windows Licensing Information
- Windows Update States (Last installed update, installed KB numbers, ...)
- Version information of proprietary software installed
- And many many more things to come 😃 

But my case is different than yours because I am deploying these scripts to the remote servers using powershell remoting, remote copy them there, create a windows task scheduler task that is periodically executing the scripts. So the script scope is then only the local host, so this is more in line with the prometheus guidelines.

I guess it would probably be easier to try to convince the manager of the remote systems to install the `wmi_exporter` , but this will probably not give you out of the box all the metrics you have in NAGIOS at the moment.

**Comment by FreddieAkeroyd** [comment]
Thank you @Mario-Hofstaetter - powershell remoting and textfile collectors sound interesting options to consider.

**Comment by fischerman** [comment]
I was looking into the approach of @Mario-Hofstaetter as well and was wondering how to monitor this integration. This is essentially a push model so we must monitor all the scripts. Luckily [there is a metric](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.textfile.md#metrics) to check the modification time of the `.prom` files in the Windows exporter. As long as the script touches the file on success (regardless of whether the data changes), just put an alert on this metric and you are good to go. This applies to local and remote Windows exporter alike.

**Comment by Mario-Hofstaetter** [comment]
> 
> 
> Luckily [there is a metric](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.textfile.md#metrics) to check the modification time of the `.prom` files in the Windows exporter. As long as the script touches the file on success (regardless of whether the data changes), just put an alert on this metric and you are good to go.

@fischerman Also be aware that missing metrics are quite tricky in prometheus. If one of the `.prom` files gets deleted somehow, the `windows_textfile_mtime_seconds` metric __disappears__ immediately.
The [`absent()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent) can be used to find _missing_ metrics and alert on them if needed, but is unpleasant to use if many jobs / instances / targets are involved.

**Comment by fischerman** [comment]
Good point! An option for many instances is this (untested) query
```
up{job="windows"} unless on(instance) windows_textfile_mtime_seconds{file="awesome_metrics.prom"}
```
which returns a vector element for all nodes which don't have the file `awesome_metrics.prom`.

**Comment by SuperQ** [comment]
There is a much easier solution to the pushgateway for this. [PushProx](https://github.com/prometheus-community/PushProx) allows client nodes to "dial home" in order for Prometheus to connect to them and scrape metrics.
