### ISSUE TITLE
mssql collector reports last metric value even when mssql service is stopped

### ISSUE THREAD

**Issue by pmvieira** [prometheus-community/windows_exporter#520]
Hi,

We have observed a strange behavior hen using the mssql collector to monitor a SQL Express installation: even when the service is stopped the collector continues to report the last value for each metric that was collected as if the mssql service was running.
Can you please clarify if this intended behaviour and/or assist us?

**Comment by Mario-Hofstaetter** [comment]
Since I didn't know, I just tried looking at windows performance monitor, and the numerous performance counters are not set to zero when stopping the sql server service, so I guess the values just freeze in place and `wmi_exporter` has no way of knowing the service is down, **as it does not actually connect to the server.**

You would need an additional _sql_exporter_ anyway since there are quite some things missing in the default `wmi_mssql_` metrics.

If you want to know if your server is `up`, you could use `sqlcmd` to test connection, example via powershell:

```powershell
Invoke-Sqlcmd -Query "SELECT 1" -ServerInstance "localhost\SQL2019" -ConnectionTimeout 3 | Out-Null;
Write-Host $?;
```
This will output `True` ✅  if the connection was successful or `False` ❌  if not.

⚠️  DO NOT USE `$LASTEXITCODE` as thats `1` in both cases here for me.

You can easily write that as a `mssql_up` metric for the `textfile` collector. Maybe this helps.

I am currenlty evaluating myself if we use one of the several `sql` exporters found here on github, or query everything with `sqlcmd` and write all to `.prom` file to consume with `wmi_exporter`.

**Comment by carlpett** [comment]
Thanks for the investigation @Mario-Hofstaetter! Agree that writing this to a file used by textfile collector would be a good and easy way to see if it is up. @pmvieira would that be sufficient for you? I think it'll be out of scope for including directly into the mssql collector.
