### ISSUE TITLE
Time metrics

### ISSUE THREAD

**Issue by basroovers** [prometheus-community/windows_exporter#532]
Since node_exporter has time metrics, why does wmi_exporter not have them yet?
I've found `Win32_PerfRawData_MicrosoftWindowsW32TimePerf_WindowsTimeService` which has the following data:
- ClockFrequencyAdjustment
- ComputedTimeOffset
- NTPClientTimeSourceCount
- NTPRoundtripDelay
- NTPServerIncomingRequests
- NTPServerOutgoingResponses

The only thing stopping me from generating a collector is that the most important metric `ComputedTimeOffset` is a `ulong`, which is a 64-bit integer. (https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/ulong-data-type)

**Comment by carlpett** [comment]
Seems like an excellent addition. Are there performance counters we could read via perflib instead of WMI?

**Comment by basroovers** [comment]
Aren't these performance counters? I mean I can also find them in the performance monitor.

```
\Windows Time Service\Clock Frequency Adjustment
\Windows Time Service\Computed Time Offset
\Windows Time Service\NTP Client Time Source Count
\Windows Time Service\NTP Roundtrip Delay
\Windows Time Service\NTP Server Incoming Requests
\Windows Time Service\NTP Server Outgoing Responses
```

**Comment by carlpett** [comment]
Most of the time there's a one-to-one mapping (and the main challenge is finding the mapping), but WMI also exposes a some stuff which doesn't have counters. So, nice that they are there. It is *a lot* more efficient to work with the counters rather than doing WMI queries, so we try to avoid adding new WMI classes (and are slowly converting existing collectors to use counters directly).

**Comment by basroovers** [comment]
I would very much like to see this available very soon. What's the next step to make this happen?

**Comment by carlpett** [comment]
Well, the absolutely fastest way would be if you would be able to contribute the collector. The `logical_disk` collector could be a good template to start from. As you've already identified the counters you need, it should be fairly straightforward.
You can always submit a pull request which isn't complete if you need some pointers!

**Comment by tahachoura** [comment]
Hi Dears, 

I have an issue please :  I added  --collectors.enabled"time"  to export NTP metrics, in order to monitor windows NTP server.
But all metrics are  0 , even though my NTP client is synchronised... 

![image](https://user-images.githubusercontent.com/11164303/125771876-a146d886-25ee-450d-8816-fb16130e7f86.png)

**Comment by breed808** [comment]
@tahachoura could you open an issue for this please?
