### ISSUE TITLE
Update Release Version on 0.13.0 to Align with Semantic Versioning "Breaking Change" Standards

### ISSUE THREAD

**Issue by james-m-tubbs** [prometheus-community/windows_exporter#537]
Hi All,

We should update the version number of the latest release from 0.13.0 to 1.0.0 (or something else) so it aligns with the semantic versioning standard for backwards incompatible changes. Since the release is going to break pretty much all promql associated with the exporter it's worth doing.

More Info: https://semver.org

**Comment by martinlindhe** [comment]
IIRC we bumped minor versions in the past for this project to indicate breaking changes.
It has also been noted in the release notes this time and in the past.

https://github.com/prometheus-community/windows_exporter/releases

**Comment by carlpett** [comment]
@james-m-tubbs Semver actually allows for pretty much anything during 0.x.
But spec technicalities aside, I do agree we should be targeting a 1.0 soonish. And probably have some sort of guidelines on what we guarantee to not break (for example, a typo in a metric name is strictly speaking a breaking change, should that then become a 2.0?).

@martinlindhe Agree! Up until now, the looming rename has been blocking a 1.0 from my point of view, so now I think it is mainly about cleaning up so we don't need to make another breaking change again soon.
There's a few things I've had in the back of my mind: 
- Merge the dotnet_* collectors. It should just have been a single one since the start, with subcollectors like we have in a couple of other places.
- Move the remaining major collectors to perflib. Main risk of breakage would be the service collector, which if I remember correctly doesn't map all that well between WMI<->perflib.

So, what do you think about this rough idea of upcoming releases?
- 0.13.x will likely be needed for fallout
- 0.14.x for the couple of outstanding PRs that came in during the rename window + changes mentioned above and anything else we figure out would be good to get done
- 1.0 :cake:

**Comment by martinlindhe** [comment]
@carlpett sounds like a solid roadmap to me!

**Comment by james-m-tubbs** [comment]
Thanks guys - appreciate it

**Comment by Zayan1221** [comment]
Hello - I need some help- I have download wmi_exporter before but did not install i guess-,

Now what should I do for this new change- Can some one help me with Download and install with this new windows_exporter on all the client windows servers , as I have prometheus,Grafana installed on Linux(CentOS 7) server and want to see the Metrics on Grafana

**Comment by carlpett** [comment]
Hi @Zayan1221,
That is quite off-topic for this issue. I would suggest posting on the [prometheus-users maillist](https://groups.google.com/forum/#!forum/prometheus-users) for help with general setup.
