### ISSUE TITLE
Error Events: Every Scrape Due To Missing "textfile_inputs" Directory

### ISSUE THREAD

**Issue by sdcote** [prometheus-community/windows_exporter#542]
## Overview
v0.13.0 generates error events every time it is scraped:
````
Error reading textfile collector directory "C:\\Program Files\\windows_exporter\\textfile_inputs": open C:\Program Files\windows_exporter\textfile_inputs: The system cannot find the path specified.
````
## Expected Behavior
Generate error when service starts, silently ignore the missing directory.

Alternately, create the directory during the install.

## Workaround:
```
mkdir  "C:\Program Files\windows_exporter\textfile_inputs"
```

**Comment by carlpett** [comment]
Hi @sdcote,
This directory is created by the installer. If you choose to roll your own installation process, you'll need to create it, however.

**Comment by sdcote** [comment]
The point of this issue is the installer apparently did not create the directory. Part of the expected behavior I wrote mentions creating the directory during the install. I did not "roll my own" installer. I use the installer from the [0.13.0 Releases](https://github.com/prometheus-community/windows_exporter/releases/tag/v0.13.0) page.

Are you implying there is an issue with the installer if that directory does not exist? If so, this issue should probably be reopened.

**Comment by carlpett** [comment]
Hi,
Apologies, I understood the report as asking for the exporter itself to create the directory, which would be outside the scope we want it to cover. The installer has been creating the textfile directory [since v0.3.0](https://github.com/prometheus-community/windows_exporter/commit/76bb06b32faacb8a610c6ab08530c13719f17f3f), so if that does not work, it'd be a bug.

If it does not work in your environment, could you run the installer with logging (eg `msiexec /i <path to msi> /l*v log.txt`) and upload them?
