### ISSUE TITLE
Easy migration path from wmi_exporter to windows_exporter

### ISSUE THREAD

**Issue by bbqrob** [prometheus-community/windows_exporter#547]
As stated [here](https://github.com/prometheus-community/windows_exporter/releases/tag/v0.13.0), the project has been renamed and now you have to change every metric name (logic stays the same). Is there an easy migration path for fixing all the new metric names in Prometheus (or even Grafana) ?

**Comment by carlpett** [comment]
There's two options, broadly:
1. For Grafana, you can write a script/small tool that uses the API to [fetch dashboard json](https://grafana.com/docs/grafana/latest/http_api/dashboard/#get-dashboard-by-uid), does a search/replace and then [updates](https://grafana.com/docs/grafana/latest/http_api/dashboard/#create-update-dashboard) the dashboard. For Prometheus, I assume you mean alerting/recording rules? Basically the same, but whereever you store your configuration.
2. If this is not feasible in your environment and you absolutely need to retain the old prefix, you can configure prometheus to rename all the new metrics to the old prefix by adapting the approach mentioned [here](https://github.com/prometheus-community/windows_exporter/issues/519#issuecomment-633249466) (in reverse, then, since that was for preparing an environment by using the new names ahead of the release)

Or am I misunderstanding your use-case?
