### ISSUE TITLE
Exchange collector returns subset of metrics with Exchange 2010

### ISSUE THREAD

**Issue by scluff** [prometheus-community/windows_exporter#569]
## Expected Behavior
Only counters which are not found should be omitted (HttpProxy and WorkloadManagement)

## Actual Behavior
Only metrics sent to the channel before an error is encountered are scraped

## Steps to Reproduce the Problem
```
[user@prometheus ~]# for i in {1..10}; do curl -s http://exchange.example.com:9182/metrics | grep windows_exchange | grep -v '# '| wc -l; sleep 1; done
0
160
0
0
1
6
170
3
0
0
```

## Specifications
  - Version: v0.13.0
  - Platform: Exchange 2010 SP3 RU17 on Windows Server 2008 R2 SP1

**Comment by scluff** [comment]
If I remove the following lines, I no longer encounter see a varying number of returned metrics.
https://github.com/prometheus-community/windows_exporter/blob/6bcaee58853ce4700b820058237501e6727530be/collector/exchange.go#L172
https://github.com/prometheus-community/windows_exporter/blob/6bcaee58853ce4700b820058237501e6727530be/collector/exchange.go#L177

**Comment by carlpett** [comment]
Hi @scluff,
Thanks for reporting! That is indeed a bug, we shouldn't be returning here, since that gives partial results:
https://github.com/prometheus-community/windows_exporter/blob/6bcaee58853ce4700b820058237501e6727530be/collector/exchange.go#L180-L183
What are the returned errors you get? Depending on what is going wrong, there's different ways to approach this.

**Comment by scluff** [comment]
I see one of these in the log:
> level=error msg="Error in HttpProxy: counter not found" source="exchange.go:181"
> level=error msg="Error in WorkloadManagement: counter not found" source="exchange.go:181"

Followed by:
> level=error msg="collector exchange failed after 0.000000s: counter not found" source="exporter.go:206"

**Comment by carlpett** [comment]
Ok, thanks. It's been many moons since I last managed Exchange servers - would I be correct in guessing that you haven't installed roles corresponding to those? What I'm looking for is really if these are expected conditions in some installs, or a sign that something is broken?
Generally speaking, if something is broken it'd be more in line with Prometheus standard behaviours to _always_ serve no metrics at all from this collector, while if it is expected, then maybe we shouldn't even log an error.

**Comment by scluff** [comment]
I am not an Exchange expert by any stretch, but from what I have read HttpProxy may be related to a feature called Outlook Anywhere; we do not have this enabled.

According to some [documentation](https://docs.microsoft.com/en-us/exchange/server-health/workload-management?view=exchserver-2019) for workload management:

> This feature was available in Exchange 2010 (known as user throttling), and was expanded to its current level in Exchange 2013.

I don't believe workload management is an optional feature - I am able to run some related PowerShell cmdlets without issue. My assumption is that the related classes simply don't exist in versions of Exchange < 2013.

**Comment by carlpett** [comment]
Ah. Then perhaps the correct path here would be doing version detection to enable just supported counters?
@eikaas / @rmyhren does this sound reasonable to you?

**Comment by garysebastiani** [comment]
Hi,
I don't know if this is related, but we are also using Exchange 2010 and 0.13.0. And we are not receiving any information neither for windows_exchange_http_* nor windows_exchange_transport_* . Do you think that's could be linked ? Or is it something totally different that would need on other issue ? To give further information, I didn't try commenting the line you show as I am not the one adminstrating the machine.

**Comment by rmyhren** [comment]
Hi all! We will have a look at this as soon as we are back from summer holidays
