### ISSUE TITLE
collector dns failed after 69.174842s: WMI query returned empty result set  

### ISSUE THREAD

**Issue by guleng** [prometheus-community/windows_exporter#571]
The exporter I use is the latest version, but I can't get the indicator of the commander DNS. I have patched it（ https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-1350 ）Then it can't be obtained normally! I am a server for Windows Server 2016

![image](https://user-images.githubusercontent.com/40238640/87894241-ca767780-ca74-11ea-9b5c-6abbeef71645.png)

**Comment by carlpett** [comment]
Hi @guleng,
The issue you are seeing is not directly within the exporter itself, but rather that your Windows installation for some reason does not have the performance counters. This can have a large number of reasons, which we can't really fix.
Something which _can_ potentially help in this situation is rebuilding your performance counters by running `lodctr /R`. Unfortunately it does not fix all issues, but is a good starting point.

Alos, From your screenshot, you seem to be running v0.8.3, rather than the latest version which is v0.13.0. I'd suggest updating to get quite a few performance fixes and new features.
