### ISSUE TITLE
Is it possible to scrape metrics from a windows target without installing windows_exporter?

### ISSUE THREAD

**Issue by paull25** [prometheus-community/windows_exporter#606]
Hi All,

I am new here so please bear with me if I posted in a wrong place.

Currently I am using windows_exporter to expose metrics from a windows server target. I just want to ask if I can scrape metrics (CPU, RAM, DISK, SERVICES) from multiple windows servers target without installing the exporter? or can I scrape metrics using a single windows_exporter probe - basically the idea is to have a single box with windows_exporter installed that can scrape metrics from other windows targets without actually installing a exporter to the targets.

Appreciate if you can enlighten and guide me with this set-up.

Thank You!

**Comment by carlpett** [comment]
Hi @paull25,
No, this is not supported. The design (shared with the vast majority of the Prometheus ecosystem, wherever possible) is meant to minimize unrelated failures impacting your monitoring. In this case, if you had a central windows_exporter instance which collected from other machines, you'd have a lot more things which could fail (more instances, more network connections). 
Since your monitoring should hopefully be the most robust piece in your infrastructure, we do not want to support the remote collection use case.
