### ISSUE TITLE
Pending connection broker connections is not a counter

### ISSUE THREAD

**Issue by fischerman** [prometheus-community/windows_exporter#655]
`windows_terminal_services_connection_broker_performance_total` is declared as a counter. This is true for successful and failed connections, but not for pending connections. That one seems to be a gauge and gives current value. For some reason I even get negative values. Not sure yet, whether this is due to the exporter or a fault in the performance counter itself.

![Screenshot from 2020-11-05 15-35-48](https://user-images.githubusercontent.com/6820657/98254594-c6675a80-1f7c-11eb-82ce-c474cea2f5c0.png)

Reference: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/mt729067(v%3Dws.11)

**Comment by fischerman** [comment]
The value is taken straight from the performance counter so I think the problem with the negative values originates in Windows. I've posted the question in the Microsoft forum: https://docs.microsoft.com/en-us/answers/questions/152865/negative-pending-connections-at-connection-broker.html

**Comment by carlpett** [comment]
Thanks for reporting!
Re the counter/gauge, we'll have to split out the pending ones into a new metric like `windows_terminal_services_connection_broker_pending_connections`, I suppose.
The Microsoft representative in your support query seems to indicate that the negative value is a bug on their end, so I'm unsure if we should try to handle that. On one hand, the value is nonsensical, but on the other hand I'm not sure we want to get into the game of trying to correct data we are reading. I would guess it's easy to make things worse rather than better.

**Comment by fischerman** [comment]
Hi @carlpett, thanks for the reminder. I didn't get a notification for the Microsoft forum. I don't quite understand the response, but than again I'm no performance counter / Windows expert by any means. For starters, it is not clear to me if performance counters are non-negative by definition and how that relates to `PDH_CALC_NEGATIVE_VALUE`.

I think we should not explicitly check for negative values in the Windows exporter. However, if I understand at least part of the explanation, then the response data should only be handled if no error is returned with it. Does the exporter perform such a check (possibly in the underlying perflib library)?
