### ISSUE TITLE
How to turn of windows_service_status collection?

### ISSUE THREAD

**Issue by MAzZYBig** [prometheus-community/windows_exporter#661]
Hi!
I want to turn of collection of windows_service_status metrics but still collect windows_service_state. I don't need the first one and think it's too excessive. 
How can I do this? Is there any possibilities?

**Comment by carlpett** [comment]
We don't support this in the exporter itself, but you can easily control this on the Prometheus side via `metric_relabel_configs`. Simply set `action: drop` when the `__name__` source label is `windows_service_status`

**Comment by MAzZYBig** [comment]
Yes, I know about it. But as it said [there](https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus):

> All the samples are still pulled from the job being scraped, so this should only be a temporary solution until you can push a fixed version of your code.

**Comment by carlpett** [comment]
What is referred to in that blog post is that "fixing" your code rather than dropping metrics is a workaround for *your own instrumented applications*, when something generates a lot more metrics than expected. In this case, the exporter is working as expected, so dropping metrics you are not interested in is ok, even as a long-term situation.

**Comment by MAzZYBig** [comment]
Ok, thanks!
