### ISSUE TITLE
Is it possible to get command line of process

### ISSUE THREAD

**Issue by Peihu2020** [prometheus-community/windows_exporter#688]
Dear developers,

I am trying to do Windows system monitor by using your windows exporter. Thanks for your tools first.

Now, my project need to monitor 8 java process which will be register corresponding serivce as well.

Currently, your tool can only detect process id of each process, but for me it is very difficult to differentiate them separately.

So, I suggest you can provide command line of each process if possible.

Thanks in advance,
Peihu

**Comment by breed808** [comment]
Hi Peihu,

If you have access to the source code of the Java processes, directly instrumenting metrics in the application with the [java client](https://github.com/prometheus/client_java) would be the best option for exposing the "real" process name, rather than a generic java exe.
Alternatively you could use the [textfile collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.textfile.md) combined with a custom script to expose this information.

Unfortunately we're not able to expose this information with the metrics provided by perflib, as perflib can only provide the name of the running process as seen by Windows (E.G. `java.exe`).

**Comment by djyin4op** [comment]
At present, you can only get command line from  WMI, but the metrics with process now providered by perflib。

**Comment by jbirkel-vk** [comment]
I'm having a similar issue.  I want to monitor a specific Python program but there may be other Python programs running and I can't tell which is which.  

For example, I'd like to monitor the process created by this command line:
>python programA.py

But not this command line"
>python programB.py

Is there a way to do that?
