### ISSUE TITLE
Windows_exporter metrics (processes)

### ISSUE THREAD

**Issue by wHiteeeeeeeee** [prometheus-community/windows_exporter#720]
Hi, I have a question regarding the metrics from windows_exporter. Is there any metric or how to run it to display information about all processes (such as teams, mozilla etc)? It seems to me that this is the private_bytes metric, unfortunately I do not have one in windows_exporter. Do you need to run it somehow?

My config.yml file:
![Screenshot_2](https://user-images.githubusercontent.com/75625585/107365092-9b8d2500-6adc-11eb-9517-11bff8af6b7c.jpg)

Thanks a lot for all answers!

**Comment by Mario-Hofstaetter** [comment]
You have to add the `process` collector to your `collectors` property in yaml.
So like this (free typing, please don't screenshot configs but rather paste them as text 😉 )

```yaml
collectors:
  enabled: cpu,cs,logical_disk,net,os,process,service,system,textfile
```

See: 
<https://github.com/prometheus-community/windows_exporter#collectors>
<https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.process.md>

**Comment by wHiteeeeeeeee** [comment]
Ok, that seems to work, but when i want to install from msi like this:
```
 msiexec /i \windows_exporter-0.15.0-amd64.exe --collectors.enabled "process" --collector.service.services-where "Name='windows_exporter'"
```
I'm reciving:
![windows installer](https://user-images.githubusercontent.com/75625585/107920105-aaf0f000-6f6c-11eb-8d07-b9ea9ad16c53.jpg)

Is that command wrong?

**Comment by Mario-Hofstaetter** [comment]
Your filter `--collector.service.services-where "Name='windows_exporter'"` does not seem useful to me.
You want to export service metrics only for the windows_exporter itself?

Anyway, **`msiexec` parameter escaping and/or powershell string escaping is a mine-field.**
This is my powershell script line:

```powershell
$argumentList = "/quiet", "/i", $setupMsi, "ENABLED_COLLECTORS=$collectors", "TEXTFILE_DIR=$TextfileDir", 'EXTRA_FLAGS="--collector.process.whitelist=""foo.+|foo.+|sql.+|SQL.+"" --collector.service.services-where=""Name LIKE ''foo%''""  "';
Start-Process -Wait -FilePath msiexec.exe -ArgumentList $argumentList
```

You should be able to adapt it to your needs.
I was not able to call msi without using `Start-Process` , did cost me hours.

**Comment by wHiteeeeeeeee** [comment]
It was just an example, there should be process name ;). But is there any option to export all processes? Or i need to specify what processes I want to extract? 
Is there any easier way to enable those collectors? Maybe any option to attach config.yml to windows_exporter? The powershella command syntax looks quite problematic :D

**Comment by Mario-Hofstaetter** [comment]
Do you want to export metrics for windows services, or running processes, or both?

By default (no filters set) all services or processes are exported if the corresponding collector is enabled.
See [`process` collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.process.md) (supports whitelist and blacklist) and [`service` collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.service.md) (supports only whitelist)

Both can be quite noisy generating timeseries, especially `process` since there are constantly windows system processes starting (or crashing ...).
But on the other hand, if a windows process is burning CPU, I would want to see that in my dashboard, not just seeing "other" processes having high CPU load.
Also if a machine starts misbehaving after a windows system serivce started or stopped I also wanna know that.

> Is there any easier way to enable those collectors? Maybe any option to attach config.yml to windows_exporter?

What do you mean by attach? How to you install / rollout the `.msi` file? You can copy the `.yml` config to any directory on the target machine. I have not yet used the config file, I don't think it existed when I first started using the exporter 🤔

**Comment by wHiteeeeeeeee** [comment]
Ok thanks for your help ;)
