### ISSUE TITLE
Textfile need help

### ISSUE THREAD

**Issue by PierreNa** [prometheus-community/windows_exporter#750]
Hi all,

I need help for create my first textfile collector.

I don't uderstand how does it work...

I want to collect the windows update available on a server Windows 2019/2016/2012 and i think i can get this information with a powershell script but i don't understand how windows_exporter get the result of the script and publish this for Prometheus...

Thanks and sorry for my bad english ...

**Comment by breed808** [comment]
Hi @PierreNa, by default the `textfile` collector will collect metrics in any `.prom` files in `C:\Program Files\windows_exporter\textfile_inputs`. You'll need to configure your Powershell script to output to a file in this directory.

There's documentation for the collector available [here](docs/collector.textfile.md).

**Comment by Mario-Hofstaetter** [comment]
@PierreNa I'll try to get you going with an example.

(I too tried exposing windows update information but gave up, because there are different ways to get different update infos in windows ("Hotfixes", "Updates", ...), damn you Microsoft)

The following powershell script gets a list of installed software and writes a `.prom` file in the necessary format.
For information on the formatting, see <https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example>

>**⚠️ DISCLAIMER: I do not guarantee this will list all installed software of your machine**
```powershell
$MetricName = 'windows_software_installed_info';

$Prom = "# HELP $MetricName List installed software via registry entries.`n" +
        "# TYPE $MetricName gauge`n";

$InstalledSoftware = Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*' |
    Where-Object DisplayName -ne $null | Select-Object DisplayName, DisplayVersion, Publisher -Unique;

$InstalledSoftware | ForEach-Object {
    $Metric = "$MetricName{display_name=`"$($_.DisplayName)`",display_version=`"$($_.DisplayVersion)`",publisher=`"$($_.Publisher)`"} 1`n";
    $Prom += $Metric;
}

Set-Content -Encoding Ascii -Value $Prom -Path "$MetricName.prom.temp";
# Rename and overwrite file in an atomic operation as fast as possible to avoid conflict with the exporter reading the file
Move-Item -Force -Path "$MetricName.prom.temp" -Destination "$MetricName.prom"
```

**Be VERY CAREFUL that every line (yes the last one!) [ends with a LINEFEED character](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details), or scraping will FAIL.**

It will generate a file called `windows_software_installed_info.prom` which then contains entries like these:
```openmetrics
# HELP windows_software_installed_info List installed software via registry entries.
# TYPE windows_software_installed_info gauge
windows_software_installed_info{display_name="Notepad++",display_version="7",publisher="Notepad++ Team"} 1
windows_software_installed_info{display_name="7-Zip 19.00 (x64 edition)",display_version="19.00.00.0",publisher="Igor Pavlov"} 1
```
The metric definition (Name, labels, ..) are of course completely up to you.

My windows_exporter runs with this start parameter:
```
--collector.textfile.directory C:\windows_exporter\textfile_collector
```
So I put the file to path: `C:\windows_exporter\textfile_collector\windows_software_installed_info.prom`
If the file format is wrong, windows_exporter will not use it. 

Make sure this metric is `0` in <http://localhost:9182/metrics>:
```text
# HELP windows_textfile_scrape_error 1 if there was an error opening or reading a file, 0 otherwise
# TYPE windows_textfile_scrape_error gauge
windows_textfile_scrape_error 0
```
After scraping in prometheus:
![grafik](https://user-images.githubusercontent.com/33002073/113480436-78f00a80-9494-11eb-84e3-f294a3dfb652.png)

To monitor if / when files have last been updated, check these metrics:
```text
# HELP windows_textfile_mtime_seconds Unixtime mtime of textfiles successfully read.
# TYPE windows_textfile_mtime_seconds gauge
windows_textfile_mtime_seconds{file="windows_software_installed_info.prom"} 1.617457409e+09
```
Use this query to check the timestamps: `time() - windows_textfile_mtime_seconds` , if the value (seconds) becomes greater than XXX, it may indicate your script / task scheduler job / ... is failing. Use this for alerting.

## Additional information

- For this kind of metadata metrics, be sure the value of the metric is always `1` and the type is a `gauge`, see:
<https://www.robustperception.io/how-to-have-labels-for-machine-roles>
<https://www.robustperception.io/why-info-style-metrics-have-a-value-of-1>
- The name suffix `_info` was optional in prometheus until now, but often seen for these kind of metrics to indicate the value is irrelevant. BUT be advised there is an actual [`Info` type in the OpenMetrics Specification](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#info-1), which will have the `_info` suffix and `1` value as a REQUIREMENT, see also [here](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#info), I believe windows_exporter does not support the OpenMetrics format, yet

**Comment by PierreNa** [comment]
Hello @Mario-Hofstaetter ,
Thanks you so much for you're answer.
It's work for windows update.
Thanks for you're time and sorry for my aswer response delay.
Regards.

**Comment by Mario-Hofstaetter** [comment]
@PierreNa would it be possible for you to share your script to get Windows Update Information?
It may be useful for the community (and me 😀 ).

**Comment by PierreNa** [comment]
Yeah but it's a simple count pf windows_update available on server.
`$MetricName = 'windows_update_available';

$Prom = "# HELP $MetricName List available udapte pending.`n" +
        "# TYPE $MetricName gauge`n";

# Count number update pending

[Int]$Count = 0;
$Searcher = new-object -com "Microsoft.Update.Searcher";
$Searcher.Search("IsAssigned=1 and IsHidden=0 and IsInstalled=0").Updates | ForEach-Object { $Count++ };

$Metric = "$MetricName $Count";
$Prom += $Metric;

Set-Content -Encoding Ascii -Value $Prom -Path "C:\Temp\$MetricName.prom.temp";
# Rename and overwrite file in an atomic operation as fast as possible to avoid conflict with the exporter reading the file
Move-Item -Force -Path "C:\Temp\$MetricName.prom.temp" -Destination "C:\config\windows_exporter\textfile_collector\$MetricName.prom"`

I will try to set an other script for list the different update available and her name.

And an other for kist only the security update i will update this ticket for that ;)
