### ISSUE TITLE
How do collectors behave when the relevant performance counters don't exist?

### ISSUE THREAD

**Issue by Wittionary** [prometheus-community/windows_exporter#754]
Hello! I have a question on collector behavior.
**Background:** I'm rolling out the windows_exporter in my Windows-heavy environment using Configuration Manager (aka SCCM) deployments and I'm wondering how tightly focused my collections need to be. That is, should I target domain controllers and have the default + ad collectors? For SQL, default + mssql? Or is it enough to enable all the collectors I want in my environment and target "Windows Servers"?

For me, I believe this could be resolved with an answer to the question "How do collectors behave when the relevant performance counters don't exist?"

Let me know if there's any additional info or context that would be important to consider.

**Comment by breed808** [comment]
>How do collectors behave when the relevant performance counters don't exist?

Where there are missing performance counters, the collector should gracefully fail. Other collectors with present counters should continue to run.
Any other behaviour should be considered a bug (see #755 for a good example).

Regarding SCCM deployments, I've previously used the default collectors (minus the `service` collector) and added role-specific collectors for groups, such as the `mssql` collector when deploying to SQL Servers.

The configuration file might make things easier, though I've not used it with SCCM yet.

**Comment by carlpett** [comment]
Just noting that while the exporter will work, there are some effects that in my experience makes it worth the time to push the "right" config to each node:
- You won't know when things "should" fail vs unexpected failures. This will make it hard to write alerts, for example.
- You'll get some logs produced on each scrape warning that some collectors failed. Over a large fleet where you probably also centralize logs, this can end up being quite a lot.

So that's at least something to consider, and weigh against the extra time you'll need to spend in SCCM to categorize your machines.

**Comment by Mario-Hofstaetter** [comment]
I too ran into the `mssql` collector issue, IIRC the performance counters are missing after a reboot, if the mssql service ist not started automatically (test server).

If the collector handles this gracefully, the metrics will just become `stale`, which makes alerting in prometheus quite tricky.
There is no general `windows_mssql_up` metric either (which I would love to see).

Is it possible to add a gauge for `mssql` collector (and other collectors concerned), that will be set to current unix timestamp, if data-collection was successful? Is it possible to read the last-written-timestamps of windows performance counters? (Sry, I'm a n00b). If there is a performance counter that is always regularly incremented by MSSQL we could utilize this.

This would be similar to
```
# HELP windows_textfile_mtime_seconds Unixtime mtime of textfiles successfully read.
# TYPE windows_textfile_mtime_seconds gauge
```
which is a **must-have** when using text-file collector.

**Comment by breed808** [comment]
The `textfile` collector requires that timestamp, as `.prom` files may not be cleaned up which causes the collector to report "fresh" metrics to Prometheus.

>If the collector handles this gracefully, the metrics will just become stale, which makes alerting in prometheus quite tricky.

Do you mean stale from Prometheus' perspective, or stale metrics reported by the collector to Prometheus which then considers them to be "fresh"?

If you mean stale from Prometheus' perspective, there is an `absent()` function that can be used to alert for missing metrics. However it's preferable to have the exporter/collector correctly report the collection status (`windows_mssql_collector_success` in this case).

If the collector is reporting stale metrics to Prometheus, that's something we should work to resolve.

**Comment by Mario-Hofstaetter** [comment]
I guess I mixed up the two things a little bit.

>If you mean stale from Prometheus' perspective, there is an `absent()` function that can be used to alert for missing metrics. 

Yes I meant the timeseries will disappear from prom after 5 minutes if series are missing from an exporter.
Which is not the case here. I find the `absent` function hard to use, because you have to know the labels up front to create the query, which is often impossible with dozens of machines.

> If the collector is reporting stale metrics to Prometheus, that's something we should work to resolve.

If `mssql` service crashes or is stopped by user, the exporter will report the last known metrics.
`windows_mssql_collector_success` is reporting success on my machine even though no SQL Server is running.
So the exporter reports "fresh" metrics although the database is down 🙈 

To know if a SQL instance is up and running, at the moment one has to use a dedicated SQL Exporter which actually _connects_ to the SQL server.

**Comment by breed808** [comment]
I've had a look at the exporter, it's checking `HKLM\Software\Microsoft\Microsoft SQL Server\Instance Names\SQL` for available instances on startup, but no further instance checks are run.

There's a number of ways to resolve this, but perhaps the simplest way would be to check if the system service for the instance is in a "running" state. If not, have the sub-collector return a failure.
E.G.
```
windows_mssql_collector_success{mssql_instance="MSSQLSERVER"} 0
```

However this would rely on a WMI query in the `mssql` collector, which we're trying to avoid.
