### ISSUE TITLE
Can I disable the metrics I'm not using?

### ISSUE THREAD

**Issue by halidsert** [prometheus-community/windows_exporter#779]
I'm using Prometheus and Grafana to monitor multiple servers. I've disabled the collectors I don't use but I'd like to disable the metrics I don't need as well. For instance, cpu collector is enabled but the only metric I'm interested is "windows_cpu_time_total". I was wondering if I can disable all the other metrics I don't need (or rather specifically enable only this metric on installation). I found out that mssql collector has a flag to enable its classes. Maybe there is no way to disable the metrics one by one but I can disable classes of the collectors I use.

**Comment by carlpett** [comment]
Hi @halidsert,
No, we don't have settings to disable individual metrics. If you want to drop certain metrics, you can do so by writing relabelings on the Prometheus service with `action: drop`.

**Comment by halidsert** [comment]
@carlpett Thank you for your reply. The main reason I asked this is that I want the exporter to not collect anything other than I want it to, thinking that would decrease its cpu usage (I'm not sure how much that would affect, if any at all).

**Comment by carlpett** [comment]
Unfortunately no, (almost all) the APIs we use will pull out all data. Your best option if you need to reduce resource usage is avoiding collectors implemented with WMI, and using filters on the collectors that support it. For the newer perflib-based collectors, CPU usage is quite modest.

**Comment by halidsert** [comment]
Thank you for the clarification.

**Comment by breed808** [comment]
> Does disabled classes unused still pull data and does it affect the resource usage in that aspect?

For the `mssql` collector specifically, disabled sub-collectors will not be run, meaning there is no resource usage or data pulled.

> If it makes difference when you don't enable a class, does that apply to other collectors as well?

The `mssql` collector has used "sub-collectors" since its inception, likely to reduce load from WMI queries and to reduce unwanted metrics on the Prometheus side of things.
Note that this is not a common collector design; most other collectors don't include sub-collectors due to their smaller size or use of Perflib, which makes query load less of a concern.
