### ISSUE TITLE
How to monitor the disk and network usage of each process in windows?

### ISSUE THREAD

**Issue by yangliyl** [prometheus-community/windows_exporter#790]
Does windows_process_io_bytes_total include disk and network usage?
If so, how do I get independent disk and network usage?

**Comment by breed808** [comment]
From the [metric description](https://github.com/prometheus-community/windows_exporter/blob/72c46664dbd73185f19b5b8b2619ea2a17b2e706/collector/process.go#L80):

> Bytes issued to I/O operations in different modes (read, write, other). This property counts all I/O activity generated by the process to include file, network, and device I/Os. Read and write mode includes data operations; other mode includes those that do not involve data, such as control operations.

So yes, the metric does include disk and network usage. However, you'll only get a combined total, so you won't know if an increase in the metric is due to file, network or disk activity.

**Comment by yangliyl** [comment]
@breed808 ok thanks.
