### ISSUE TITLE
windows metrics different with linux metric

### ISSUE THREAD

**Issue by FunkyYang** [prometheus-community/windows_exporter#792]
I wan't to collect it ,and collected to prometheus and show on grafana.I find some metric changed it's name .so any one could help

**Comment by breed808** [comment]
Can you provide more context on your issue? What errors or problems are you experiencing?

**Comment by Tall-Paul** [comment]
I suspect this is the same issue I'm having, in that the metric names for this exporter are completely different to the metric names from the linux 'node exporter', so it's not possible to have single queries pulling back stats from both without a lot of work remapping them all.

For example, I have a query like this in a grafana dashboard:

((avg by (instance) (node_memory_MemTotal_bytes{job="node"}) - avg by (instance) (node_memory_MemAvailable_bytes{job="node"})) / (avg by (instance) (node_memory_MemTotal_bytes{job="node"}) )) * 100

Which gives me the percentage memory free on linux nodes, but (obviously) doesn't work on windows nodes because those metrics don't exist but (I assume) those actual values for total memory & free memory exist on windows in different metrics.

**Comment by breed808** [comment]
Yes, this is due to differences in the operating systems such as different exporter prefixes, keeping to metric names provided by Microsoft in WMI/Perflib, etc.

Keeping the metric names closely aligned to those of `node_exporter` would be rather difficult for little gain, so it's never been a design goal of `windows_exporter`.
