### ISSUE TITLE
collector.process.whitelist is not work

### ISSUE THREAD

**Issue by veer123prathap** [prometheus-community/windows_exporter#814]
I use the following command to collect metrics for the chrome process, but its metrics do not include windows_ process
`"\"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182 --collectors.enabled "[defaults],memory,process,tcp" --collector.process.whitelist='chrome.+'"`

**When I remove the --collector.process.whitelist option, it can normally collect the windows_process indicator**

**Comment by breed808** [comment]
You'll want to change the regex from `chrome.+` to `chrome.*`

**Comment by louij2** [comment]
Have you worked out how to do this yet? Following documentation and the below doesn't fix the issue. When there is no whitelist I don't see any processes at all. I want to see which process is hogging the CPU. Thanks

**Comment by breed808** [comment]
> When there is no whitelist I don't see any processes at all

This would suggest you're experiencing a different issue. Are you receiving any error output from the exporter? Does the `process` collector report success when querying the exporter?

**Comment by louij2** [comment]
`# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 68063.8125
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.6777216e+07
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 427
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 3.8567936e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.620916648e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 3.534848e+07`

**Comment by breed808** [comment]
Could you provide the metrics you are seeing?

**Comment by louij2** [comment]
> Could you provide the metrics you are seeing?

https://hastebin.com/zocidejoqi.log

**Comment by louij2** [comment]
I tried to do the whitelist but does not work for me either

**Comment by louij2** [comment]
Say I wanted to monitor Java memory usage. I just whitelist --collector.process.whitelist="java.+|JAVA.+"
![image](https://user-images.githubusercontent.com/2940588/128853397-c13873af-d523-4adf-8eb7-af763b3c9d8f.png)

**Comment by louij2** [comment]
--config.file=win_exporter.yml --collector.process.whitelist="agentwrap.*|DistMan.*|GeoService.*|SessionServer.*" here's my arguments

**Comment by louij2** [comment]
Sorry I worked it out now. Ignore my previous. Thanks Just wrote down the whitelist in all caps and in lowercase
