### ISSUE TITLE
Feature Request: Append current user to labels

### ISSUE THREAD

**Issue by proffalken** [prometheus-community/windows_exporter#852]
Hey,

We're starting to use this in anger and it's awesome, however there's one thing that appears to be missing and I can't see an obvious config flag to enable it at run-time.

At the moment, we're looking at `process_cpu_time_total` for specific processes in a virtual desktop environment.

As an example, `process_cpu_time_total{process="EXCEL"}` returns details about the CPU time used by Excel, however the only labels available to us are:

   * `creating_process_id`
   * `instance`
   * `job`
   * `mode`
   * `process`
   * `process_id`

It would be amazing if we could also get the currently logged in user as a label as well, that way we can link it back to other metrics that we have with that label and examine the user experience.

**Comment by breed808** [comment]
There's no user field in the Perflib metric source that we currently use for the `process` collector, so another source would have to be found in order to implement this.

Another item we need to consider is the [cardinality](https://www.robustperception.io/cardinality-is-key) of the metrics. There's already the `process`, `process_id` and `creating_process_id` labels in use, and we'll need to ensure the addition of a `user` label doesn't cause any performance issues.

If someone can find a suitable source, I'd be happy to look at this further. PRs are always welcome too :smiley:

**Comment by breed808** [comment]
Alternatively we could expose a separate user metric and the two could be joined with PromQL.
