### ISSUE TITLE
Grafana template

### ISSUE THREAD

**Issue by eliassal** [prometheus-community/windows_exporter#931]
Hi, is there somewhere any Grafana template that uses the metrics collected by this exporter? Thanks

**Comment by breed808** [comment]
We don't provide an official Grafana template for the exporter, but we're open to submissions if you find anything appropriate.

Due to the large number of metrics exposed by this exporter, a simple dashboard containing the default metrics (CPU, memory, disk usage, network bandwidth, etc) would be a good starting point for anyone interested in contributing.

**Comment by Oscaramr** [comment]
I didnt make this but you can try this one https://grafana.com/grafana/dashboards/14694
